### ISSUE TITLE
代码验证问题

### ISSUE THREAD

**Issue by haizhu12** [leftthomas/EGFF#1]
你好 ，感谢你们做出如此优秀的工作，我运行了你们的代码，但出现了运行时警告，并且在验证时出现了| P@100:nan% | P@200:nan% ，没有修改参数，环境配置也一样，请问您知道是啥原因吗？图示：
![20220615113329](https://user-images.githubusercontent.com/93024130/173731383-819e4fbc-9839-4521-90c4-15c0a54000f8.png)

**Comment by leftthomas** [comment]
@haizhu12 you should check you exactly use the same hyper-parameters, the data and the library version.

**Comment by haizhu12** [comment]
@leftthomas windows 10  python 3.8 pytorch 1.10.1 num_works=2 其他超参未作修改 依然出问题，在sketch 和tuberlin上都是一样 ，请问你们用的是否是python3.8版本，还有，你们可以提供一下你们的Pre-trained model吗?，十分感谢

**Comment by leftthomas** [comment]
@haizhu12 we have released the pre-trained models, you should look `readme` carefully.

**Comment by leftthomas** [comment]
@haizhu12 according to the warning, I think you maybe not follow our `readme` to organize the dataset structure.

**Comment by haizhu12** [comment]
@leftthomas  是下载了你们的数据集，dataset structure应该没问题 ，我断点调试后发现warning的位置，val验证阶段 在acc计算的compute_metric中photo_vectors得到的是一个空列表，然后导致utils.py 75行出问题，请问这个怎么解决啊，十分感谢。见图示：
![QQ截图20220615163625](https://user-images.githubusercontent.com/93024130/173784673-d5660228-e085-4b57-a0d3-4c823d0603fb.png)
![QQ截图20220615163825](https://user-images.githubusercontent.com/93024130/173784715-f5bb24ba-cc39-4ef6-b912-75989bc83e69.png)

**Comment by leftthomas** [comment]
@haizhu12 It's obvious that you haven't loaded any photos at all. Please check whether the structure of your dataset is consistent with that described by `readme`.

**Comment by haizhu12** [comment]
@leftthomas 反复检查dataset 是没问题的，按照readme格式，而且我debug发现val_loader 是读出了photo的，不知道为什么后面photo_vectors就成了空列表了， 见图示：
![5](https://user-images.githubusercontent.com/93024130/173838863-5aa1bde6-7cd6-4f42-8390-66138d3c4649.png)
![40](https://user-images.githubusercontent.com/93024130/173839797-bc2ddd76-0a26-4c15-b5f4-827213914eed.png)

**Comment by leftthomas** [comment]
@haizhu12 you should be more familiar with `linux` and `windows`, that the path split not same:
https://github.com/leftthomas/EGFF/blob/5fa5ca2aa6724f46717a3c0be66ca310a1422324/utils.py#L49

**Comment by haizhu12** [comment]
@leftthomas 十分感谢，代码在linux上正确运行,我将深入研究你们的论文
